create table achat (id bigint not null auto_increment, prix float(53), quantite integer not null, commande_id bigint, produit_id bigint, primary key (id));
create table adresse (id bigint not null auto_increment, code_postal varchar(10), rue varchar(200) not null, ville varchar(150), primary key (id));
create table commande (id bigint not null auto_increment, dt_commande datetime(6), etat enum ('ENCOURS','TERMINEE','CONFIRMEE','EXPEDIEE'), prix_total float(53), client_id bigint, primary key (id));
create table commentaire (id bigint not null auto_increment, detail varchar(255), dt_commentaire datetime(6) not null, note integer not null, client_id bigint, produit_id bigint, primary key (id));
create table fournisseur_adresse (fournisseur_id bigint not null, adresse_id bigint not null);
create table personne (type varchar(15) not null, id bigint not null auto_increment, civilite enum ('M','MME','MLLE'), email varchar(255), nom varchar(255) not null, dt_naissance date, prenom varchar(255), responsable varchar(200), utilisateur_id bigint, adresse_id bigint, primary key (id));
create table produit (id bigint not null auto_increment, modele varchar(100), nom varchar(150), prix float(53), ref varchar(100), fournisseur_id bigint, primary key (id));
create table utilisateur (id bigint not null auto_increment, active bit not null, identifiant varchar(50) not null, mot_de_passe varchar(200) not null, primary key (id));
create table utilisateur_roles (utilisateur_id bigint not null, role enum ('CLIENT','FOURNISSEUR','ADMIN','SUPER_ADMIN') not null, primary key (utilisateur_id, role));
alter table personne add constraint UK_personne_utilisateur_id unique (utilisateur_id);
alter table personne add constraint UK_personne_adresse_id unique (adresse_id);
alter table utilisateur add constraint UK_utilisateur_identifiant unique (identifiant);
alter table achat add constraint FK_achat_commande_id foreign key (commande_id) references commande (id);
alter table achat add constraint FK_achat_produit_id foreign key (produit_id) references produit (id);
alter table commande add constraint FK_commande_client_id foreign key (client_id) references personne (id);
alter table commentaire add constraint FK_commentaire_client_id foreign key (client_id) references personne (id);
alter table commentaire add constraint FK_commentaire_produit_id foreign key (produit_id) references produit (id);
alter table fournisseur_adresse add constraint FK_fournisseur_adresse_adresse_id foreign key (adresse_id) references adresse (id);
alter table fournisseur_adresse add constraint FK_fournisseur_adresse_fournisseur_id foreign key (fournisseur_id) references personne (id);
alter table produit add constraint FK_produit_fournisseur_id foreign key (fournisseur_id) references personne (id);
alter table utilisateur_roles add constraint FK_utilisateurs_roles_utilisateur_id foreign key (utilisateur_id) references utilisateur (id);
